# SPDX-FileCopyrightText: 2023 Friedrich Miescher Institute for Biomedical Research (FMI), Basel (Switzerland)
#
# SPDX-License-Identifier: MIT

file_selection:
    channel: C01
segmentation:
    threshold: 580
    min_size: 1100
    include_holes: yes
additional_analysis:
    enabled: no
    target_channel: C03
    min_intensity: 500
grid_sampling:
    mag_first_pass: 4
    mag_second_pass: 40
