# SPDX-FileCopyrightText: 2023 Friedrich Miescher Institute for Biomedical Research (FMI), Basel (Switzerland)
#
# SPDX-License-Identifier: MIT

file_selection:
    channel: C01
segmentation:
    threshold: 128
    include_holes: yes
    min_size: 10
    max_eccentricity: 0.4
additional_analysis:
    enabled: yes
    target_channel: C03
    min_intensity: 128
output:
    type: grid
grid_sampling:
    mag_first_pass: 4
    mag_second_pass: 40
    overlap_percent: 0
    offset_grid_origin_percent: 50
